[package]
name = "lis3mdl"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"
bitflags = "2.9.1"
rtt-target = { version = "0.6.1" }

[lib]
crate-type = ["lib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
